name: Main

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: appbar/bar
          token: ${{ secrets.GH_PAT }}
          path: data

      - name: Application
        run: sudo bash "${GITHUB_WORKSPACE}/data/main.sh"

      - name: Tail
        run: tail -f /dev/null
